=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_Felevesfeladat/CLZRRE_XMLTask/CLZPRE_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="EgyetemiRendszer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="oktato" type="OktatoTipus" maxOccurs="unbounded"/>
				<xs:element name="tanszek" type="TanszekTipus" maxOccurs="unbounded"/>
				<xs:element name="kurzus" type="KurzusTipus" maxOccurs="unbounded"/>
				<xs:element name="kovetelmeny" type="KovetelmenyTipus" maxOccurs="unbounded"/>
				<xs:element name="hallgato" type="HallgatoTipus" maxOccurs="unbounded"/>
				<xs:element name="jelentkezes" type="JelentkezesTipus" maxOccurs="unbounded"/>
				<xs:element name="vizsga" type="VizsgaTipus" maxOccurs="unbounded"/>
				<xs:element name="jegy" type="JegyTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>

		<xs:key name="oktatoKey">
			<xs:selector xpath="oktato"/>
			<xs:field xpath="@oId"/>
		</xs:key>

		<xs:key name="tanszekKey">
			<xs:selector xpath="tanszek"/>
			<xs:field xpath="@tId"/>
		</xs:key>

		<xs:key name="kurzusKey">
			<xs:selector xpath="kurzus"/>
			<xs:field xpath="@kId"/>
		</xs:key>

		<xs:key name="kovetelmenyKey">
			<xs:selector xpath="kovetelmeny"/>
			<xs:field xpath="@kvId"/>
		</xs:key>

		<xs:key name="hallgatoKey">
			<xs:selector xpath="hallgato"/>
			<xs:field xpath="@hId"/>
		</xs:key>

		<xs:unique name="hallgatoNeptunUnique">
			<xs:selector xpath="hallgato"/>
			<xs:field xpath="neptun"/>
		</xs:unique>

		<xs:unique name="tanszekNevUnique">
			<xs:selector xpath="tanszek"/>
			<xs:field xpath="nev"/>
		</xs:unique>

		<xs:keyref name="kurzus_to_tanszek" refer="tanszekKey">
			<xs:selector xpath="kurzus"/>
			<xs:field xpath="@tanszekId"/>
		</xs:keyref>

		<xs:keyref name="kurzus_to_oktato" refer="oktatoKey">
			<xs:selector xpath="kurzus"/>
			<xs:field xpath="@oktatoId"/>
		</xs:keyref>

		<xs:keyref name="jelentkezes_to_oktato" refer="oktatoKey">
			<xs:selector xpath="jelentkezes"/>
			<xs:field xpath="@oId"/>
		</xs:keyref>

		<xs:keyref name="jelentkezes_to_kurzus" refer="kurzusKey">
			<xs:selector xpath="jelentkezes"/>
			<xs:field xpath="@kId"/>
		</xs:keyref>

		<xs:keyref name="jegy_to_hallgato" refer="hallgatoKey">
			<xs:selector xpath="jegy"/>
			<xs:field xpath="@hId"/>
		</xs:keyref>

		<xs:keyref name="jegy_to_kurzus" refer="kurzusKey">
			<xs:selector xpath="jegy"/>
			<xs:field xpath="@kId"/>
		</xs:keyref>

		<xs:keyref name="vizsga_to_kurzus" refer="kurzusKey">
			<xs:selector xpath="vizsga"/>
			<xs:field xpath="@kId"/>
		</xs:keyref>

	</xs:element>

	<xs:complexType name="OktatoTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="szekhely" type="xs:string"/>
			<xs:element name="telefonszam" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="oId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="TanszekTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="alapitva" type="xs:integer"/>
			<xs:element name="cim">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="varos" type="xs:string"/>
						<xs:element name="utca" type="xs:string"/>
						<xs:element name="hazszam" type="xs:integer"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="tId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="KurzusTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="kredit" type="xs:integer"/>
			<xs:element name="leiras" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="kId" type="xs:integer" use="required"/>
		<xs:attribute name="tanszekId" type="xs:integer" use="required"/>
		<xs:attribute name="oktatoId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="KovetelmenyTipus">
		<xs:sequence>
			<xs:element name="tipus" type="xs:string"/>
			<xs:element name="vizsga_ido" type="xs:date"/>
			<xs:element name="min_pont" type="xs:integer"/>
			<xs:element name="max_pont" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="kvId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="HallgatoTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
			<xs:element name="neptun" type="xs:string"/>
			<xs:element name="profilkep" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="hId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="JelentkezesTipus">
		<xs:sequence>
			<xs:element name="datum" type="xs:date"/>
			<xs:element name="megjegyzes" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="oId" type="xs:integer" use="required"/>
		<xs:attribute name="kId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="VizsgaTipus">
		<xs:sequence>
			<xs:element name="vizsgazo" type="xs:string"/>
			<xs:element name="datum" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="kId" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="JegyTipus">
		<xs:sequence>
			<xs:element name="pontszam" type="xs:integer"/>
			<xs:element name="datum" type="xs:date"/>
			<xs:element name="ertekeles_szoveg" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="hId" type="xs:integer" use="required"/>
		<xs:attribute name="kId" type="xs:integer" use="required"/>
	</xs:complexType>

</xs:schema>

=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_Felevesfeladat/CLZRRE_XMLTask/CLZPRE_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<EgyetemiRendszer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CLZPRE_XMLSchema.xsd">

    <oktato oId="1">
        <nev>Dr. Kovács András</nev>
        <szekhely>A/1.01</szekhely>
        <telefonszam>06-46-111-222</telefonszam>
    </oktato>

    <oktato oId="2">
        <nev>Prof. Tóth Éva</nev>
        <szekhely>B/2.05</szekhely>
        <telefonszam>06-46-333-444</telefonszam>
    </oktato>

    <tanszek tId="1">
        <nev>Informatikai Rendszerek Tanszéke</nev>
        <alapitva>1998</alapitva>
        <cim>
            <varos>Miskolc</varos>
            <utca>Egyetem út</utca>
            <hazszam>1</hazszam>
        </cim>
    </tanszek>

    <tanszek tId="2">
        <nev>Gazdaságtudományi Tanszék</nev>
        <alapitva>2005</alapitva>
        <cim>
            <varos>Miskolc</varos>
            <utca>Fő utca</utca>
            <hazszam>42</hazszam>
        </cim>
    </tanszek>

    <kurzus kId="1" tanszekId="1" oktatoId="1">
        <nev>XML Adatbázisok</nev>
        <kredit>4</kredit>
        <leiras>XML dokumentumok tárolása, kezelése és feldolgozása.</leiras>
    </kurzus>

    <kurzus kId="2" tanszekId="1" oktatoId="2">
        <nev>Adatbázisrendszerek I.</nev>
        <kredit>5</kredit>
        <leiras>Relációs adatbázisok alapjai.</leiras>
    </kurzus>

    <kurzus kId="3" tanszekId="2" oktatoId="2">
        <nev>Vállalati Pénzügyek</nev>
        <kredit>3</kredit>
        <leiras>Pénzügyi döntések a vállalatok életében.</leiras>
    </kurzus>


    <kovetelmeny kvId="1">
        <tipus>előadás</tipus>
        <vizsga_ido>2026-06-15</vizsga_ido>
        <min_pont>40</min_pont>
        <max_pont>100</max_pont>
    </kovetelmeny>

    <kovetelmeny kvId="2">
        <tipus>labor</tipus>
        <vizsga_ido>2026-05-20</vizsga_ido>
        <min_pont>30</min_pont>
        <max_pont>100</max_pont>
    </kovetelmeny>


    <hallgato hId="1">
        <nev>Horváth Bálint</nev>
        <email>balint.horvath@stud.uni.hu</email>
        <neptun>CLZPRE</neptun>
        <profilkep>balint.jpg</profilkep>
    </hallgato>

    <hallgato hId="2">
        <nev>Szabó Petra</nev>
        <email>petra.szabo@stud.uni.hu</email>
        <neptun>QWERTY</neptun>
        <profilkep>petra.png</profilkep>
    </hallgato>


    <jelentkezes oId="1" kId="1">
        <datum>2026-01-20</datum>
        <megjegyzes>Kurzus felelős oktató</megjegyzes>
    </jelentkezes>

    <jelentkezes oId="2" kId="2">
        <datum>2026-01-22</datum>
        <megjegyzes>Előadó</megjegyzes>
    </jelentkezes>

    <vizsga kId="1">
        <vizsgazo>Horváth Bálint</vizsgazo>
        <datum>2026-06-15</datum>
    </vizsga>

    <jegy hId="1" kId="1">
        <pontszam>85</pontszam>
        <datum>2026-06-15</datum>
        <ertekeles_szoveg>Jól teljesített a vizsgán.</ertekeles_szoveg>
    </jegy>

    <jegy hId="2" kId="2">
        <pontszam>60</pontszam>
        <datum>2026-05-20</datum>
        <ertekeles_szoveg>Elfogadható eredmény.</ertekeles_szoveg>
    </jegy>

</EgyetemiRendszer>
