=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_1008/CLZPRE_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:simpleType name="NapTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hétfő"/>
            <xs:enumeration value="Kedd"/>
            <xs:enumeration value="Szerda"/>
            <xs:enumeration value="Csütörtök"/>
            <xs:enumeration value="Péntek"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IdoTipus">
        <xs:restriction base="xs:time"/>
    </xs:simpleType>

    <xs:simpleType name="TipusTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Előadás"/>
            <xs:enumeration value="Gyakorlat"/>
            <xs:enumeration value="Gyak. íd.nyelvi okt.k"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="IdopontTipus">
        <xs:sequence>
            <xs:element name="nap" type="NapTipus"/>
            <xs:element name="tol" type="IdoTipus"/>
            <xs:element name="ig" type="IdoTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OraTipus">
        <xs:sequence>
            <xs:element name="targy" type="xs:string"/>
            <xs:element name="idopont" type="IdopontTipus"/>
            <xs:element name="helyszin" type="xs:string"/>
            <xs:element name="oktato" type="xs:string"/>
            <xs:element name="szak" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="tipus" type="TipusTipus" use="required"/>
    </xs:complexType>

    <xs:element name="CLZPRE_orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ora" type="OraTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="OraIDKulcs">
            <xs:selector xpath="ora"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

</xs:schema>

=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_0917/2feladat/CLZPRE_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="orarend.xsl"?>

<CLZPRE_orarend
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="CLZPRE_orarend.xsd">

    <ora id="1" tipus="Előadás"><targy>El.technika-elektronika</targy><idopont><nap>Hétfő</nap><tol>08:00</tol><ig>09:00</ig></idopont><helyszin>BIII A4 fsz.</helyszin><oktato>Szabó Norbert</oktato><szak>G 3BIFW</szak></ora>
    <ora id="2" tipus="Előadás"><targy>El.technika-elektronika</targy><idopont><nap>Hétfő</nap><tol>09:00</tol><ig>10:00</ig></idopont><helyszin>BIII A4 fsz.</helyszin><oktato>Szabó Norbert</oktato><szak>G 3BIFW</szak></ora>
    <ora id="3" tipus="Előadás"><targy>Web technológiák 1</targy><idopont><nap>Hétfő</nap><tol>10:00</tol><ig>11:00</ig></idopont><helyszin>V A1 magasfsz3-4</helyszin><oktato>Agárdi Anita</oktato><szak>G 3BIFW</szak></ora>
    <ora id="4" tipus="Előadás"><targy>Web technológiák 1</targy><idopont><nap>Hétfő</nap><tol>11:00</tol><ig>12:00</ig></idopont><helyszin>V A1 magasfsz3-4</helyszin><oktato>Agárdi Anita</oktato><szak>G 3BIFW</szak></ora>
    <ora id="5" tipus="Gyak. íd.nyelvi okt.k"><targy>Műszaki szaknyelv 1</targy><idopont><nap>Hétfő</nap><tol>12:00</tol><ig>13:00</ig></idopont><helyszin>A1/314 A1 elm. 314</helyszin><oktato>Gyak. Vez.</oktato><szak>G 3BIFW</szak></ora>
    <ora id="30" tipus="Előadás"><targy>Webes adatkezelő környezetek</targy><idopont><nap>Szerda</nap><tol>15:00</tol><ig>16:00</ig></idopont><helyszin>In/101 I. e. 101</helyszin><oktato>Dr. Bednarik László</oktato><szak>G 3BIFW</szak></ora>

</CLZPRE_orarend>
