=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_0924/CLZPRE_mozi.dtd
<!ELEMENT mozi (film*)>

<!ELEMENT film (rendezo+, (kategoria | hossz | bemutato)+, szinesz+)>

<!ATTLIST film
    id ID #REQUIRED
    cim CDATA #REQUIRED
    mufaj (Sci-fi | Akció | Vígjáték) #REQUIRED  >

<!ELEMENT rendezo (#PCDATA)>
<!ELEMENT kategoria (#PCDATA)>
<!ELEMENT hossz (#PCDATA)>
<!ELEMENT bemutato EMPTY>

<!ELEMENT szinesz (szerep, (gyerekszinesz | musicalsinesz | szinkronszinesz)?)>
<!ATTLIST szinesz
    nev CDATA #REQUIRED
    id ID #IMPLIED
>
<!ELEMENT szerep (#PCDATA)>
<!ELEMENT gyerekszinesz EMPTY>
<!ELEMENT musicalsinesz EMPTY>
<!ELEMENT szinkronszinesz EMPTY>

=== EgyedMartin/CLZPRE_XMLTask/CLZPRE_0924/CLZPRE_mozi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mozi SYSTEM "CLZPRE_mozi.dtd">
<mozi>
    <film id="f101" cim="Mátrix" mufaj="Sci-fi">
        <rendezo>Wachowski Fivérek</rendezo>
        <kategoria>Sci-fi</kategoria>
        <hossz>136 perc</hossz>
        <bemutato/>
        <szinesz nev="Keanu Reeves" id="k7r_a3s_2j">
            <szerep>Neo</szerep>
            <gyerekszinesz/>
        </szinesz>
    </film>
    
    </mozi>
